"use client";

import { ethers } from "ethers";
import Providers from "./components/Providers";
import { Statusbar } from "./components/Statusbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { createContext, useState } from "react";
import Web3 from "web3";
import styled from "styled-components";
import { RecoilRoot } from "recoil";

export const AppContext = createContext();

const inter = Inter({ subsets: ["latin"] });
const web3 = new Web3(process.env.NEXT_PUBLIC_WEB3_PROVIER);

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [account, setAccount] = useState();

  return (
    <html lang="en">
      <body>
        <RecoilRoot>
          <Container>
            <AppContext.Provider value={{ account, setAccount, web3 }}>
              <Providers>{children}</Providers>
            </AppContext.Provider>
          </Container>
        </RecoilRoot>
      </body>
    </html>
  );
}

const Container = styled.div`
  background-color: #121212;
  width: 100%;
  color: white;
  height: 105vh;

  display: flex;
  /* justify-content: center; */
  align-items: center;
  flex-direction: column;
`;
